services:
  prometheus:
    image: bitnami/prometheus
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus-config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml"

  grafana:
    image: "grafana/grafana"
    ports: 
      - "3000:3000"
    container_name: grafana-container

  h2db:
    build: ./h2db
    ports:
      - "8082:8082"
    container_name: h2db-container
    restart: always

  shipper-service:
    build: ./shipper-service
    container_name: shipper-service-container
    ports:
      - "8100:8080"
    environment:
      - "DB_HOST=h2db"
    depends_on: 
      - h2db
    restart: always

  customer-service:
    build: ./customer-service
    container_name: customer-service-container
    ports:
      - "8200:8080"
    environment:
      - "DB_HOST=h2db"
    depends_on:
      - h2db
    restart: always


  category-service:
    build: ./category-service
    container_name: category-service-container
    ports:
      - "8300:8080"
    environment:
      - "DB_HOST=h2db"
    depends_on:
      - h2db
    restart: always


  supplier-service:
    build: ./supplier-service
    container_name: supplier-service-container
    ports:
      - "8400:8080"
    environment:
      - "DB_HOST=h2db"
    depends_on:
      - h2db
    restart: always



  product-service:
    build: ./product-service
    container_name: product-service-container
    ports:
      - "8500:8080"
    environment:
      - "DB_HOST=h2db"
      - "CATEGORY_SERVICE_HOST=category-service"
      - "SUPPLIER_SERVICE_HOST=supplier-service"
    depends_on:
      - h2db
    restart: always

  order-service:
    build: ./order-service
    container_name: order-service-container
    ports:
      - "8600:8080"
    environment:
      - "DB_HOST=h2db"
      - "PRODUCT_SERVICE_HOST=product-service"
      - "SHIPPER_SERVICE_HOST=shipper-service"
      - "CUSTOMER_SERVICE_HOST=customer-service"
    depends_on:
      - h2db
    restart: always

  
