server:
  port: ${SERVER_PORT:8200}
  
banner: banner.txt

spring:
  applicaiton:
    name: SUPPLIER-SERVICE
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://${DB_HOST:localhost}/~/${DB_NAME:northwind}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Welcome#123}
    